# Site settings
title: Rome wiki
url: "https://Voyager003.github.io"
baseurl: ""
description: >
    기록을 남기는 중입니다.

# My information
email: miraclex000@gmail.com
author: Rome
profile: 기록을 남기는 중입니다.
twitter_username: refreshment0
github_username: Voyager003
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: voyager003
  shortname: voyager003
utterances:
  repo: voyager003/voyager003.github.io
  issue-term: url
  label: Comment
  branch: master

google_analytics:
  ua: SAMPLE-VALUE
  encrypted_ua: THIS-IS-SAMPLE-VALUE

google_adsense:
  client: SAMPLE-VALUE

blame: "https://github.com/voyager003/voyager003.github.io/blame/master/_wiki"
edit: "https://github.com/voyager003/voyager003.github.io/edit/master/_wiki"
issue: "https://github.com/voyager003/voyager003.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
